# Generated by Django 5.2.3 on 2025-07-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
