repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=100]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-docstrings
          - flake8-quotes
        args: [--max-line-length=100]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-python-dateutil
          - django-stubs
          - djangorestframework-stubs
        args: [--ignore-missing-imports]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
      - id: curlylint
        types: [file]
        files: \.(html|djhtml)$

  - repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
      - id: djhtml
        args: [--tabwidth=2]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, css, scss, json, yaml]
        additional_dependencies:
          - prettier@2.8.8

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        additional_dependencies:
          - stylelint@14.9.1
          - stylelint-config-standard@26.0.0

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.42.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.42.0
          - eslint-config-prettier@8.8.0
          - "@typescript-eslint/eslint-plugin@5.59.9"
          - "@typescript-eslint/parser@5.59.9"

  - repo: local
    hooks:
      - id: django-check
        name: django-check
        entry: python manage.py check --deploy
        language: system
        types: [python]
        pass_filenames: false

      - id: django-check-migrations
        name: django-check-migrations
        entry: python manage.py makemigrations --check --dry-run
        language: system
        types: [python]
        pass_filenames: false

      - id: django-test
        name: django-test
        entry: python manage.py test
        language: system
        types: [python]
        pass_filenames: false

default_language_version:
  python: python3

ci:
  autofix_commit_msg: "🎨 [pre-commit.ci] Auto format from pre-commit.com hooks"
  autoupdate_commit_msg: "⬆ [pre-commit.ci] pre-commit autoupdate"
  skip: []

exclude: |
  (?x)(
    ^static/|
    ^media/|
    ^docs/|
    ^.venv/|
    ^venv/|
    ^.env
  )
