# Generated by Django 5.2.3 on 2025-07-09 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Phone')),
                ('billing_first_name', models.CharField(default='', max_length=100, verbose_name='First name')),
                ('billing_last_name', models.CharField(default='', max_length=100, verbose_name='Last name')),
                ('billing_address', models.CharField(default='', max_length=250, verbose_name='Address')),
                ('billing_apartment', models.CharField(blank=True, max_length=100, verbose_name='Apartment')),
                ('billing_city', models.CharField(default='', max_length=100, verbose_name='City')),
                ('billing_state', models.CharField(default='', max_length=100, verbose_name='State')),
                ('billing_postal_code', models.CharField(default='', max_length=20, verbose_name='Postal code')),
                ('billing_country', models.CharField(default='', max_length=100, verbose_name='Country')),
                ('different_shipping', models.BooleanField(default=False, verbose_name='Different shipping address')),
                ('shipping_first_name', models.CharField(blank=True, max_length=100, verbose_name='First name')),
                ('shipping_last_name', models.CharField(blank=True, max_length=100, verbose_name='Last name')),
                ('shipping_address', models.CharField(blank=True, max_length=250, verbose_name='Address')),
                ('shipping_apartment', models.CharField(blank=True, max_length=100, verbose_name='Apartment')),
                ('shipping_city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('shipping_state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal code')),
                ('shipping_country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shipping cost')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tax')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('order_notes', models.TextField(blank=True, verbose_name='Order notes')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Tracking number')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
