# Generated by Django 5.2.3 on 2025-07-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_featured_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorpayout',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Alert when stock falls below this number', verbose_name='Low stock alert threshold'),
        ),
        migrations.AddField(
            model_name='product',
            name='manage_stock',
            field=models.BooleanField(default=True, help_text='Track inventory for this product', verbose_name='Manage stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='simple_stock',
            field=models.PositiveIntegerField(default=0, help_text='Use this for simple products. For products with sizes/colors, use variants instead.', verbose_name='Stock (for products without variants)'),
        ),
        migrations.DeleteModel(
            name='VendorOrder',
        ),
        migrations.DeleteModel(
            name='VendorPayout',
        ),
        migrations.DeleteModel(
            name='VendorProfile',
        ),
    ]
