# Generated by Django 5.2.3 on 2025-07-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_vendorpayout_vendor_remove_vendorprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mega_menu_column_title',
            field=models.CharField(blank=True, help_text='Custom title for mega menu column (leave blank to use category name)', max_length=100, verbose_name='Mega Menu Column Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='mega_menu_icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon class (e.g., fa-tshirt)', max_length=50, verbose_name='Mega Menu Icon'),
        ),
        migrations.AddField(
            model_name='category',
            name='mega_menu_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in mega menu (lower numbers appear first)', verbose_name='Mega Menu Order'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_mega_menu',
            field=models.BooleanField(default=False, help_text='Display this category in the mega dropdown menu', verbose_name='Show in Mega Menu'),
        ),
    ]
